### ISSUE TITLE
Not worked out-of-the-box

### ISSUE THREAD

**Issue by danielgiljara** [kokspflanze/ZfcSitemap#1]
Hello, first of all, I think I'm creating the first issue.

As title says, I've installed the software with composer require and using the option to inject the configuration on my config, it has "buena pinta" (it has appeareance to perform well).

When I go to /sitemap.xml I get the following error page code:

    error on line 6 at column 111: xmlParseEntityRef: no name

**Comment by danielgiljara** [comment]
I think I've found the problem to the solution. I've an & in the title, when is better to have &amp; (for if you want this suggest to improve your software, I not time to PR).

**Comment by danielgiljara** [comment]
Now I've the error:

    error on line 17 at column 92: Opening and ending tag mismatch: link line 0 and head

**Comment by danielgiljara** [comment]
I think I'm not generating HTML due to standards. Are the author or any other heper interested to catch my case in a peer programming session to incorporate all this casuistics?

**Comment by kokspflanze** [comment]
hi can you post the complete xml?

normal the xml generation is from zend-navigation, but i will check it, but i need your xml.

on monday i can check it

**Comment by danielgiljara** [comment]
Hello, how can I get the generated XML from the zend-navigation? I've
installed your component again but I don't find in the code where
zend-navigation is used.

Monday is a good for me.

**Comment by kokspflanze** [comment]
did you create the navigation with zend-navigation? 
https://docs.zendframework.com/zend-navigation/quick-start/

i mean the sitemap xml, when you open sitemap.xml

**Comment by danielgiljara** [comment]
Hi,

No, I'm using the default template provided by zend mvc skeleton.

Maybe should be this? But the first error
changed when I modified the title at layout.phtml

I'm writting on mobile.

**Comment by kokspflanze** [comment]
hi, you have to use zend-navigation, the sitemap will not work without.

**Comment by danielgiljara** [comment]
Ok, I understand. I think is thing of zend-navigation too as it worked when I changed at <title> & by & amp;

For the moment I generated sitemap.xml handly.

Thanks for your support. I close the issue.
