### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Mecanik** [kokspflanze/ZfcSitemap#2]
How does the event manager know about dynamic pages ? For example blog posts.

**Comment by kokspflanze** [comment]
you need a method to get all blgo posts, and give them to the `AbstractContainer`.

i think its easier with an example

EventManager (sure factory is missing)
````php
<?php

namespace App\Core\Listener;

use App\Core\Service;
use Zend\EventManager\AbstractListenerAggregate;
use Zend\EventManager\EventManagerInterface;
use Zend\EventManager\EventInterface;
use Zend\Navigation\AbstractContainer;
use ZfcSitemap\Service\Sitemap;

class SitemapBlog extends AbstractListenerAggregate
{
    /** @var Service\Blog */
    protected $blog;

    /**
     * SitemapBlog constructor.
     * @param Service\Blog $blog
     */
    public function __construct(Service\Blog $blog)
    {
        $this->blog = $blog;
    }

    /**
     * @inheritDoc
     */
    public function attach(EventManagerInterface $events, $priority = 1)
    {
        $this->listeners[] = $events->attach(Sitemap::EVENT_SITEMAP, [$this, 'onDispatch'], $priority);
    }

    /**
     * @param EventInterface $event
     */
    public function onDispatch(EventInterface $event)
    {
        /** @var AbstractContainer $container */
        $container = $event->getParam('container');

        foreach ($this->blog->getBlogEntries() as $blog) {
            $container->addPage([
                'route' => 'App/blog/detail',
                'params' => [
                    'market' => strtolower($blog->getName()),
                ],
                'resource' => 'App/blog/detail',
                'changefreq' => 'hourly',
                'priority' => '1.0',
            ]);
        }

        $event->setParam('container', $container);
    }

}
````


Config:

````php
    'zfc-sitemap' => [
        'strategies' => [
            Listener\SitemapBlog::class,
        ],
    ],
````

**Comment by Mecanik** [comment]
I understand, thanks. This is what I suspected however I wasn't sure, and while this addon is amazing to have, it would cause problems on big websites. If we get all "blog" posts on every dispatch, well just imagine... 500 x dispatch having 500k "blog posts" for example...

Would it not be better to have it via a cron and using the console ?

**Comment by kokspflanze** [comment]
i just tested it with 4k entries^^
but i cache the sitemap via a ngnix for 24h.

**Comment by Mecanik** [comment]
Yes well not everyone can do this, or know how to do this, and on top of this a module like this is very much wanted for custom websites.

I'm working on something big now and would love to have this working properly, I'm willing to help you extend it if you would like ?

**Comment by kokspflanze** [comment]
if you want sure.
next week i have a bit time to add smth like a cache based on a cron.

**Comment by kokspflanze** [comment]
feature added as test version, https://github.com/kokspflanze/ZfcSitemap/pull/3
i will also create a release in next hour.
